### PR TITLE
Build extra images

### PR DESCRIPTION
**Pull request by kimoonkim**
Builds a few extra images:
- init container
- file staging server
- shuffle service

### CODE REVIEW

**Comment by erikerlandson** [comment]
LGTM

**Comment by kimoonkim** [comment]
Thanks @erikerlandson for the review!

Varun, can you please take a look at this?

**Comment by varunkatta** [comment]
LGTM. Thanks for the change.

**Comment by kimoonkim** [comment]
Thanks @varunkatta. Merging soon.

**Comment by erikerlandson** [comment]
oops, sorry @kimoonkim

**Comment by kimoonkim** [comment]
No problem @erikerlandson Thanks for merging in!

**Pull request merged**
